fix compiler complain about `strptime`
from @facchinm :
compilation fails due to
`/home/travis/Arduino/libraries/MKRGSM/src/GSM.cpp:340:7: error: 'strptime' was not declared in this scope` 
which is in fact fixed by `_XOPEN_SOURCE patch`